- name: Pull and Run docker image
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Pull image
      docker_image:
        name: ausollet/calculator
        pull: yes